# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-08 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='голосующий'),
        ),
        migrations.DeleteModel(
            name='UserGolos',
        ),
    ]
